version: "3.9"

services:
  app:
    build: .
    container_name: spring-api
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mongo
    container_name: spring-mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      
volumes:
  data: {}

networks:
  default:
    name: mongodb_network